### ISSUE TITLE
[BUG] Unable to run the Snakemake -j6 example after installation from the env file (Ubuntu)

### ISSUE THREAD

**Issue by ajipratama14** [OSeMOSYS/osemosys_global#180]
### Conda environment check

- [X] I have tried using the `osemosys-global` conda environment.

### Current Behavior

Hi I want to use the OSeMOSYS global for modelling energy systems in Indonesia. However, I encounter some problems. It seems that the snakemake example couldn't be run on my laptop. Do you know why this issue happened? Attached are the snapshot of the errors and also the logdetail. Thanks!
[timeslice.log](https://github.com/user-attachments/files/15807652/timeslice.log)
[demand_projections.log](https://github.com/user-attachments/files/15807653/demand_projections.log)
[powerplant.log](https://github.com/user-attachments/files/15807654/powerplant.log)

<img width="949" alt="error 3" src="https://github.com/OSeMOSYS/osemosys_global/assets/145935831/e9bcc145-ff64-4246-a4ae-caa2c8477671">
<img width="950" alt="error 2" src="https://github.com/OSeMOSYS/osemosys_global/assets/145935831/dabb865a-0c0d-47d0-9b6f-8ee6348ff4ba">
<img width="948" alt="error1" src="https://github.com/OSeMOSYS/osemosys_global/assets/145935831/b4a418c6-b254-43e1-9608-3e65ccac1836">

### Steps To Reproduce

1. Running this OSeMOSYS in Ubuntu
2. Already installed all the glpk and solvers (CBC, CPLEX).
3. The log detail says "ModuleNotFoundError: No module named 'osemosys_global'"

### Operating System

Linux

### Log output

```shell
Traceback (most recent call last):
  File "C:\Users\sap123\osemosys_global\workflow\scripts\osemosys_global\powerplant_data.py", line 20, in <module>
    from utils import apply_dtypes
  File "C:\Users\sap123\osemosys_global\workflow\scripts\osemosys_global\utils.py", line 6, in <module>
    from osemosys_global.constants import SET_DTYPES
ModuleNotFoundError: No module named 'osemosys_global'


Traceback (most recent call last):
  File "C:\Users\sap123\osemosys_global\workflow\scripts\osemosys_global\demand_projection.py", line 7, in <module>
    import world_bank_data as wb
ModuleNotFoundError: No module named 'world_bank_data'

Traceback (most recent call last):
  File "C:\Users\sap123\osemosys_global\workflow\scripts\osemosys_global\TS_data.py", line 19, in <module>
    from osemosys_global.utils import apply_timeshift
ModuleNotFoundError: No module named 'osemosys_global'
```

**Comment by trevorb1** [comment]
Hi @ajipratama14; thanks for submitting the issue!

I have just merged in a PR that should fix some package issues we ran into a couple weeks ago; including the `ModuleNotFoundError: No module named 'osemosys_global'` error. Are you able to try and pull the latest fix (from the master branch) and try the install again and let me know if that fixes the issue. I dont recall seeing the `ModuleNotFoundError: No module named 'world_bank_data'` error on my side before, but maybe the latest PR will address that to. 

Apologies for the install issues, and thank you for reporting!

**Comment by ajipratama14** [comment]
Hi @trevorb1 ,

Thanks for the answer!
For the ModuleNotFoundError: No module named 'world_bank_data' is already solved on my side. But, the ModuleNotFoundError: No module named 'osemosys_global' is still happening. I already tried to pull the new PR, but seems the problem still exists. Please see the attached log.
[demand_projections.log](https://github.com/user-attachments/files/15808198/demand_projections.log)
[powerplant.log](https://github.com/user-attachments/files/15808199/powerplant.log)
[timeslice.log](https://github.com/user-attachments/files/15808200/timeslice.log)

**Comment by maartenbrinkerink** [comment]
Hi @ajipratama14. Could you try removing the osemosys-global package from your env file and reinstall with `pip install git+https://github.com/OSeMOSYS/osemosys_global@master` and try again?

**Comment by trevorb1** [comment]
Or, to add to @maartenbrinkerink's answer, can you try just doing `pip install .` from the root directory

**Comment by maartenbrinkerink** [comment]
@ajipratama14 You're welcome! @trevorb1 Unfortunately that does seem to imply that our installation issues for Ubuntu based on the env file are not fully fixed :( I suggest to keep this issue open for the time being.

**Comment by trevorb1** [comment]
@maartenbrinkerink; I updated install instructions to use mamba (following @abhishek0208's suggestion) and everything worked fine now. I tested on a fresh install of Ubuntu and I did not need the additional gcc install steps. If you run into any more install issues, please feel free to reopen though!
